### ISSUE TITLE
Please add the ability to get the generated version as an output of the action

### ISSUE THREAD

**Issue by Maelstromeous** [jpb06/bump-package#41]
In my workflow I want to use your action to calculate the new version number, so it can be used for publishing a new GitHub release.

However at this time I am unable to leverage your action to calculate the version number and store that as an variable for later use in the workflows.

**Comment by jpb06** [comment]
Hello!

Sorry, I missed these issues. I will take a look 🙇🏻

**Comment by jpb06** [comment]
https://github.com/jpb06/bump-package/pull/42

**Comment by jpb06** [comment]
Released as [2.5.23](https://github.com/jpb06/bump-package/releases/tag/v2.5.23). Let me know how it rolls 🙇🏻

**Comment by Maelstromeous** [comment]
Awesome thank you!

**Comment by jpb06** [comment]
Using output would look like this:
https://github.com/jpb06/bump-package/blob/6cc15942c6fad5255c8564f0068adfbf28c6f47b/.github/workflows/bump-version.yml#L49

```yaml
- name: Display action output
  run: |
    echo "Bump performed: ${{ steps.bumping-version.outputs.bump-performed }}"
    echo "New version: ${{ steps.bumping-version.outputs.new-version }}"
```
